language: cpp
dist: trusty
sudo: false

compiler:
    - g++

addons:
    apt:
        sources:
            - boost-latest
            - ubuntu-toolchain-r-test
        packages:
            - build-essential
            - libboost1.55-all-dev
            - libboost1.55-tools-dev
            - libssl-dev
            - g++-5
            - gcc-5

before_install:
    - openssl aes-256-cbc -K $encrypted_9a56aef8f4d0_key -iv $encrypted_9a56aef8f4d0_iv -in tests/ezio.pem.enc -out tests/ezio.pem -d
    - chmod 600 tests/ezio.pem
    - eval $(ssh-agent)
    - ssh-add tests/ezio.pem
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi
    - bash tests/before_install.sh
    - export LIBTORRENT=$PWD/libtorrent-rasterbar/build/
    - export LIBRARY_PATH=$LIBTORRENT/lib/:$LIBRARY_PATH
    - export CPLUS_INCLUDE_PATH=$LIBTORRENT/include/:$CPLUS_INCLUDE_PATH

install:
    - sed -i 's/g++/g++-5/g' Makefile
    - bash tests/install.sh

before_script:
    - bash tests/before_script.sh

script:
    - bash tests/script.sh
    - bash tests/deploy.sh
